apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: thorntail-istio-routing-service
spec:
  hosts:
  - thorntail-istio-routing-service
  http:
  - route:
    - destination:
        host: thorntail-istio-routing-service
        subset: a
      weight: 30
    - destination:
        host: thorntail-istio-routing-service
        subset: b
      weight: 70
