apiVersion: config.istio.io/v1alpha2
kind: RouteRule
metadata:
  name: name-service-routes
spec:
  destination:
    name: wfswarm-istio-ab-testing-name
  route:
    - labels:
        version: a
      weight: 10
    - labels:
        version: b
      weight: 90
